# Generated by Django 4.2.2 on 2024-01-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_alter_championshiphistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='championship.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='events', to='championship.team'),
        ),
    ]
