# Generated by Django 4.2.2 on 2024-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_alter_competition_competitors_alter_event_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
