# Generated by Django 4.2.2 on 2024-02-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_competition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_wicket',
            field=models.BooleanField(default=False),
        ),
    ]
